INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('GASOLINA COMUM',5.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('GASOLINA PREMIUM',6.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('OLEO DIESEL S500',4.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('OLEO DIESEL S10',5.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('ETANOL',4.99,13.00);

INSERT INTO TANQUE(ID_COMBUSTIVEL,DESCRICAO)VALUES(1,'TANQUE 01');
INSERT INTO TANQUE(ID_COMBUSTIVEL,DESCRICAO)VALUES(3,'TANQUE 02');

INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(1,'BOMBA 01');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(1,'BOMBA 01');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(2,'BOMBA 03');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(2,'BOMBA 04');
