CREATE GENERATOR GEN_COMBUSTIVEL_ID;

CREATE TABLE COMBUSTIVEL (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(20) NOT NULL,
    VALOR NUMERIC(15, 2) NOT NULL,
    IMPOSTO NUMERIC(15, 2) NOT NULL
);

ALTER TABLE COMBUSTIVEL
ADD CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY (ID);

CREATE OR ALTER TRIGGER COMBUSTIVEL_BI FOR COMBUSTIVEL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_combustivel_id,1);
end
^
SET TERM ; ^

CREATE GENERATOR GEN_TANQUE_ID;

CREATE TABLE TANQUE (
    ID              INTEGER NOT NULL,
    ID_COMBUSTIVEL  INTEGER,
    DESCRICAO       VARCHAR(20) NOT NULL
);

ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE PRIMARY KEY (ID);

ALTER TABLE TANQUE ADD CONSTRAINT FK_TANQUE_ID_COMBUSTIVEL FOREIGN KEY (ID_COMBUSTIVEL) REFERENCES COMBUSTIVEL (ID);

CREATE OR ALTER TRIGGER TANQUE_BI FOR TANQUE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_tanque_id,1);
end
^
SET TERM ; ^

CREATE GENERATOR GEN_BOMBA_ID;

CREATE TABLE BOMBA (
    ID         INTEGER NOT NULL,
    ID_TANQUE  INTEGER,
    DESCRICAO  VARCHAR(20) NOT NULL
);

ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA PRIMARY KEY (ID);

ALTER TABLE BOMBA ADD CONSTRAINT FK_BOMBA_ID_TANQUE FOREIGN KEY (ID_TANQUE) REFERENCES TANQUE (ID);

CREATE OR ALTER TRIGGER BOMBA_BI FOR BOMBA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_bomba_id,1);
end
^
SET TERM ; ^

CREATE GENERATOR GEN_ABASTECIMENTO_ID;

CREATE TABLE ABASTECIMENTO (
    ID        INTEGER NOT NULL,
    ID_BOMBA  INTEGER,
    VALOR     NUMERIC(15,2) NOT NULL,
    LITROS    NUMERIC(15,2) NOT NULL,
    IMPOSTO   NUMERIC(15,2) NOT NULL,
    DATA      TIMESTAMP NOT NULL
);

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO PRIMARY KEY (ID);

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_ID_BOMBA FOREIGN KEY (ID_BOMBA) REFERENCES BOMBA (ID);

CREATE OR ALTER TRIGGER ABASTECIMENTO_BI FOR ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_abastecimento_id,1);
end
^
SET TERM ; ^

INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('GASOLINA COMUM',5.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('GASOLINA PREMIUM',6.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('OLEO DIESEL S500',4.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('OLEO DIESEL S10',5.95,13.00);
INSERT INTO COMBUSTIVEL(DESCRICAO,VALOR,IMPOSTO)VALUES('ETANOL',4.99,13.00);

INSERT INTO TANQUE(ID_COMBUSTIVEL,DESCRICAO)VALUES(1,'TANQUE 01');
INSERT INTO TANQUE(ID_COMBUSTIVEL,DESCRICAO)VALUES(3,'TANQUE 02');

INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(1,'BOMBA 01');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(1,'BOMBA 01');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(2,'BOMBA 03');
INSERT INTO BOMBA(ID_TANQUE,DESCRICAO)VALUES(2,'BOMBA 04');